#@name get-prompts
GET http://localhost:3333/prompts

###

#@name list-prompts
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="prøve.mp3"
Content-Type: audio/mpeg

< ./prøve.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/2cab26f1-1934-4531-aa2d-b8d105d32243/transcription
Content-Type: application/json

{
  "prompt": "concurrenciais, praticas"
}

###

# @name generate-ai-completion
POST http://localhost:3333/videos/2cab26f1-1934-4531-aa2d-b8d105d32243/transcription
Content-Type: application/json

{
  "prompt": "concurrenciais, praticas"
}